# Generated by Django 5.2.4 on 2025-07-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfume', models.CharField(max_length=30)),
                ('popular', models.BooleanField()),
                ('acordesPrincipales', models.TextField()),
                ('acordePrincipal', models.CharField(max_length=30)),
                ('fotosReales', models.TextField()),
                ('fotosCatalogo', models.TextField()),
            ],
        ),
    ]
