# Generated by Django 5.2.4 on 2025-08-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfumes',
            name='original',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfumes',
            name='perfume',
            field=models.CharField(max_length=50),
        ),
    ]
