# Generated by Django 5.2.4 on 2025-08-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0002_perfumes_original_alter_perfumes_perfume'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfumes',
            name='estacionesRecomendadas',
            field=models.TextField(default=''),
        ),
    ]
