# Generated by Django 5.2.4 on 2025-08-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0003_perfumes_estacionesrecomendadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfumes',
            name='casa',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='perfumes',
            name='acordePrincipal',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='perfumes',
            name='acordesPrincipales',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfumes',
            name='estacionesRecomendadas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='perfumes',
            name='fotosCatalogo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfumes',
            name='fotosReales',
            field=models.TextField(blank=True),
        ),
    ]
