# Generated by Django 5.2.4 on 2025-08-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0004_perfumes_casa_alter_perfumes_acordeprincipal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfumes',
            name='precio',
            field=models.TextField(default=''),
        ),
    ]
