# Generated by Django 5.2.5 on 2025-08-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0005_perfumes_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfumes',
            name='diminutivo',
            field=models.CharField(default='', max_length=20),
        ),
    ]
