# Generated by Django 5.2.5 on 2025-09-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0006_perfumes_diminutivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfumes',
            name='disponibile',
            field=models.BooleanField(default=True),
        ),
    ]
