# Generated by Django 5.2.5 on 2025-09-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0007_perfumes_disponibile'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfumes',
            name='genero',
            field=models.CharField(default=''),
        ),
    ]
