# Generated by Django 5.2.5 on 2025-09-18 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0008_perfumes_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfumes',
            old_name='disponibile',
            new_name='disponible',
        ),
    ]
