# Generated by Django 5.2.5 on 2025-09-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0009_rename_disponibile_perfumes_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfumes',
            name='precio',
            field=models.IntegerField(default=3500),
        ),
    ]
