# Generated by Django 5.2.5 on 2025-09-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0011_alter_perfumes_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfumes',
            name='cantidad',
            field=models.CharField(default='100 ml', max_length=20),
        ),
    ]
