# Generated by Django 5.2.5 on 2025-09-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0012_perfumes_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfumes',
            name='precioDolar',
            field=models.BooleanField(default=False),
        ),
    ]
