# Generated by Django 5.2.5 on 2025-09-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0014_alter_perfumes_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfumes',
            name='precio',
            field=models.TextField(default=''),
        ),
    ]
