# Generated by Django 5.2.5 on 2025-09-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0015_alter_perfumes_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfumes',
            name='precio',
            field=models.IntegerField(default=''),
        ),
    ]
