# Generated by Django 5.2.5 on 2025-09-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0016_alter_perfumes_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfumes',
            name='genero',
            field=models.CharField(default='', max_length=20),
        ),
    ]
